name: Exemple d'Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Exécuter le script
      env:
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
        MONGO_COLLECTION_NAME: ${{ secrets.MONGO_COLLECTION_NAME }}
        MONGO_APP_NAME : ${{ secrets.MONGO_APP_NAME }}
      run: |
        echo "MONGO_USER : $MONGO_USER" 
        echo "MONGO_PASSWORD : MONGO_PASSWORD" 
        echo "MONGO_HOST : MONGO_HOST" 
        echo "MONGO_DBNAME : MONGO_DBNAME" 
        echo "MONGO_COLLECTION_NAME : MONGO_COLLECTION_NAME" 
        echo "MONGO_APP_NAME : MONGO_APP_NAME" 
